### PR TITLE
set knighting round price manually

### PR DESCRIPTION
**Pull request by jalbrekt85**
handles #12 

note: function signature for setting price differs in [`citadel-contracts`](https://github.com/Citadel-DAO/citadel-contracts/blob/main/src/KnightingRound.sol#L331)

### CODE REVIEW

**Comment by petrovska-petro** [comment]
will advise on holding on this pr till we get a clear picture of how the prices will be updated during the knight rounds and at which cadence. imo would make sense to leverage the [oracles](https://github.com/Citadel-DAO/citadel-contracts/tree/main/src/oracles) that have being built for assets and try to derive prices from those. but will like to hear the opinion from @dapp-whisperer on the final setup

**Comment by jalbrekt85** [comment]
> will advise on holding on this pr till we get a clear picture of how the prices will be updated during the knight rounds and at which cadence. imo would make sense to leverage the [oracles](https://github.com/Citadel-DAO/citadel-contracts/tree/main/src/oracles) that have being built for assets and try to derive prices from those. but will like to hear the opinion from @dapp-whisperer on the final setup
> 
> Open q's at my end are:
> 
> * price of ctdl against the assets of the rounds are dynamic, so i guess that will affect on the value `tokenOutPerTokenIn` despite that being initialised at some rate

agreed, will convert to draft and iterate on it as needed

**Review by jorijnsmit — APPROVED** [review]
lgtm

**Review by petrovska-petro — APPROVED** [review]
lgtm & merging!

**Pull request merged**
